# Generated by Django 6.0.2 on 2026-03-01 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('category', models.CharField(choices=[('REGISTRATION', 'Alumni Registration'), ('MONTHLY', 'Monthly Contribution'), ('WELLWISHER', 'Wellwisher/Donation'), ('CHALLENGE', 'Challenge/Fundraiser'), ('OTHER', 'Other')], default='REGISTRATION', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
